version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/barchasb_db
      - SECRET_KEY=barchasb_secret_key
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  postgres:
    image: postgres:15  # PostgreSQL version
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_USER: admin         # Replace with your desired username
      POSTGRES_PASSWORD: admin     # Replace with your desired password
      POSTGRES_DB: barchasb_db      # Replace with your database name
    ports:
      - "5432:5432"                        # Expose PostgreSQL on default port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d barchasb_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4                  # PGAdmin image
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Admin email for PGAdmin
      PGADMIN_DEFAULT_PASSWORD: admin          # Admin password for PGAdmin
    ports:
      - "5050:80"                             # Expose PGAdmin on port 5050
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin        # Persist PGAdmin data
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
    driver: local                            # Volume for PostgreSQL data
  pgadmin_data:
    driver: local                            # Volume for PGAdmin data